/*
 * generated by Xtext
 */
package jp.ac.kyushu_u.iarch.archdsl.ui.contentassist

import jp.ac.kyushu_u.iarch.archdsl.ui.contentassist.AbstractArchDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ArchDSLProposalProvider extends AbstractArchDSLProposalProvider {
}
